const teamList = [
  {
    name: 'Darshan Patel',
    position: 'Creative Leader',
    phoneNumber: '930 60 290',
    email: 'celine.sagenes@greyglobal.no',
    subdivision: 'reklame_design',
    id: '0',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Luis Villasmil',
    position: 'Communication advisor',
    phoneNumber: '917 40 710',
    email: 'kjetil.vaehle@greyglobal.no',
    subdivision: 'reklame_design',
    id: '1',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Logan Weaver',
    position: 'Senior Project Manager/Advisor',
    phoneNumber: '977 69 057',
    email: 'elisabeth.ringdal@greyglobal.no',
    subdivision: 'reklame_design',
    id: '2',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Charlie Green',
    position: 'Art Director',
    phoneNumber: '906 06 409',
    email: 'hege.thoresen@greyglobal.no',
    subdivision: 'reklame_design',
    id: '3',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Hazel Aksoy',
    position: 'Senior PR-adviser',
    phoneNumber: '909 55 441',
    email: 'vidar@greyglobal.no',
    subdivision: 'pr_content',
    id: '4',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Yunming Wang',
    position: 'Senior PR',
    phoneNumber: '473 09 794',
    email: 'anita@greyglobal.no',
    subdivision: 'pr_content',
    id: '5',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Ben Parker',
    position: 'Senior Communications Advisor',
    phoneNumber: '918 71 366',
    email: 'hanne@greyglobal.no',
    subdivision: 'pr_content',
    id: '6',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Jeffery Erhunse',
    position: 'Jr. Communication advisor / social media',
    phoneNumber: '411 00 340',
    email: 'sissel.jarulf@greyglobal.no',
    subdivision: 'pr_content',
    id: '7',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Michael Damina',
    position: 'Working Chairman',
    phoneNumber: '977 69 057',
    email: 'elisabeth.ringdal@greyglobal.no',
    subdivision: 'admin.',
    id: '8',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Leilani Angel',
    position: 'Daglig leder / Group CEO',
    phoneNumber: '996 98 753',
    email: 'morten.wasa@greyglobal.no',
    subdivision: 'admin.',
    id: '9',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Omid Armin',
    position: 'Agency Manager',
    phoneNumber: '918 55 412',
    email: 'eirik@greyglobal.no',
    subdivision: 'admin.',
    id: '10',
    image: '/youinweb/static/images/team',
  },
  {
    name: 'Toa Heftiba',
    position: 'IT consultant-consultant',
    phoneNumber: '905 94 046',
    email: 'arne.thorbeck@greyglobal.no',
    subdivision: 'admin.',
    id: '11',
    image: '/youinweb/static/images/team',
  },


]

export default teamList;